apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.tls: "false"
spec:
  rules:
  - host: argocd.jlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infraestructura
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: base/core
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/datos
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: application
metadata:
  name: herramientas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/herramientas
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitorizacion
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/monitorizacion
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/portal
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-logs-single
    targetRevision: 0.12.4
    helm:
      values: |
        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitorizacion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-metrics-single
    targetRevision: 0.17.0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitorizacion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    chart: crowdsec
    targetRevision: 0.24.0
    helm:
      values: |
        bouncer:
          enabled: true
          existingSecret: "crowdsec-bouncer-key"
          service:
            name: traefik
            namespace: kube-system
        acquisition:
          - source: k8s-logs
            label: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
