apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Infraestructura
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Datos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/datos
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Herramientas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/herramientas
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Monitorización
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/monitorizacion
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/javilaf05/k3-gitops.git'
    targetRevision: HEAD
    path: apps/portal
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
