apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: default
spec:
  type: NodePort 
  selector:
    app: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      nodePort: 30053  
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      nodePort: 30053 
      protocol: TCP
    - name: web-ui
      port: 80
      targetPort: 3000
      protocol: TCP
