apiVersion: v1
kind: Service
metadata:
  name: adguard-service
  namespace: default
spec:
  selector:
    app: adguard-home
  ports:
    - name: ui
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
