apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-net-traefik
  namespace: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knative-net-traefik
  template:
    metadata:
      labels:
        app: knative-net-traefik
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: knative-net-traefik
        image: ghcr.io/knative/net-traefik/cmd/controller:v1.13.0
        securityContext:
          privileged: true
