apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-operator
  namespace: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      dash: knative-operator
  template:
    metadata:
      labels:
        dash: knative-operator
    spec:
      containers:
      - name: knative-operator
        image: gcr.io/knative-releases/knative.dev/operator/cmd/operator:v1.13.0
