apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitorizacion
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://vmsingle-victoriametrics-victoria-metrics-k8s-stack.monitorizacion.svc.cluster.local:8428
        access: proxy
      - name: victoriametrics-logs-datasource
        type: loki
        url: http://victorialogs-victoria-logs-single-server.monitorizacion.svc.cluster.local:9428
        access: proxy
        jsonData:
          timeout: 60
          maxLines: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitorizacion
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
          name: grafanaport
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "1234"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources/
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitorizacion
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitorizacion
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: grafana.jlc.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-service
            port:
              number: 80
