apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.0.0
    helm:
      values: |
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: s3
            s3:
              endpoint: http://minio-service.default.svc.cluster.local:9000
              bucketnames: loki-logs
              access_key_id: minioadmin
              secret_access_key: minioadmin
              s3forcepathstyle: true
              insecure: true
        singleBinary:
          replicas: 1
        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitorizacion 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
