apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitorizacion
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: victoriametrics-metrics-datasource
        type: prometheus
        url: http://victoriametrics-victoria-metrics-single-server.monitorizacion.svc.cluster.local:8428
        access: proxy
      - name: victoriametrics-logs-datasource
        type: loki
        url: http://victorialogs-victoria-logs-single-server.monitorizacion.svc.cluster.local:9428
        access: proxy
        jsonData:
          timeout: 60
          maxLines: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-bridge
  namespace: monitorizacion
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8428
    targetPort: 8428
    protocol: TCP
  selector:
    app.kubernetes.io/instance: victoria-metrics
    app.kubernetes.io/name: victoria-metrics-single

