apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    chart: victoria-logs-single
    targetRevision: 1.50.0 
    helm:
      values: |
        server:
          extraArgs:
            - "-retentionPeriod=7d"
        persistence:
          enabled: true
          size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitorizacion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
