apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitorizacion
spec:
  serviceAccountName: vmagent-sa
  remoteWrite:
    - url: "http://victoriametrics-victoria-metrics-single-server.monitorizacion.svc.cluster.local:8428/api/v1/write"
  volumes:
    - name: config-volume
      configMap:
        name: victoriametrics-config
  volumeMounts:
    - name: config-volume
      mountPath: /etc/vmagent/
