apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale 
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 0.20.0
    chart: tailscale-operator
    helm:
      releaseName: tailscale-operator
      values: |
        operatorConfig:
          apiServerProxyConfig:
            mode: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
