apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc        
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  
  resources:
    requests:
      storage: 10Gi          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      hostAliases:
        - ip: "192.168.164.200"  
          hostnames:
            - "collabora.jlc.local"
      containers:
      - name: nextcloud
        image: nextcloud:latest
        ports:
        - containerPort: 80
          name: http
        volumeMounts:        
        - name: nextcloud-data
          mountPath: /var/www/html 
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:               
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - http:
      paths:
      - path: /nextcloud 
        pathType: Prefix
        backend:
          service:
            name: nextcloud-service
            port:
              number: 80
