apiVersion: apps/v1
kind: Deployment
metadata:
  name: silverbullet
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: silverbullet
  template:
    metadata:
      labels:
        app: silverbullet
    spec:
      containers:
      - name: silverbullet
        image: zefhemel/silverbullet:latest
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: silverbullet-space
          mountPath: /space
      volumes:
      - name: silverbullet-space
        persistentVolumeClaim:
          claimName: silverbullet-pvc
