apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://crowdsecurity.github.io/helm-charts
    chart: crowdsec
    targetRevision: 0.24.0 
    helm:
      values: |
        bouncer:
          enabled: true
          existingSecret: "crowdsec-bouncer-key"
          service:
            name: traefik
            namespace: kube-system
        acquisition:
          - source: docker
            container_name: traefik
            labels:
              type: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
