apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-db-cluster
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 3Gi
    storageClass: local-path
