apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: homelab-db-daily-backup
  namespace: default
spec:
  immediate: true
  schedule: "0 2 * * *"
  cluster:
    name: homelab-db-cluster
