apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: default
  namespace: tailscale
spec:
  # Si el operador insiste en que spec no puede estar vacío, 
  # intenta añadir una etiqueta vacía:
  workloadSelectors: []
