apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: default
  namespace: tailscale
spec:
  # Esto le dice al operador que use este grupo para los Ingress
  # que no especifiquen un grupo concreto.
