apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.68.0
    helm:
        values: |
          operatorConfig:
            apiServerProxyConfig:
              mode: "true"
              secretName: "operator-oauth"
          # Intenta forzar el borrado de cualquier override añadiendo esto:
          command: []
          args: []
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
