apiVersion: tailscale.com/v1alpha1
kind: Tailnet
metadata:
  name: test-tailnet
  namespace: tailscale
spec:
  # Esto es un ejemplo, el operador intentará procesarlo
  # y registrará un error o una acción en los logs
