apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vaultwarden-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vaultwarden
  minReplicaCount: 0 
  maxReplicaCount: 2   
  cooldownPeriod: 600  
  pollingInterval: 30  
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://vmsingle-vm-stack.monitorizacion.svc.cluster.local:8428
      metricName: traefik_service_requests_total
      query: sum(rate(traefik_service_requests_total{service=~"vaultwarden-service.*"}[5m]))
      threshold: '1'
