apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
        - containerPort: 4000
        env:
        - name: CONFIG_PATH
          value: /app/public/conf.yml
        volumeMounts:
        - name: config
          mountPath: /app/public/conf.yml
          subPath: conf.yml
      volumes:
      - name: config
        configMap:
          name: dashy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  conf.yml: |
    appConfig:
      title: Mi Dashboard Móvil
    sections:
      - name: Servicios Internos
        items:
          - title: Nextcloud
            icon: fas fa-cloud
            link: http://10.43.209.85 # IP Nextcloud
          - title: Trilium
            icon: fas fa-book
            link: http://10.43.106.212 # IP Trilium
          - title: IT-Tools
            icon: fas fa-tools
            link: http://10.43.58.242 # IP IT-Tools
---
apiVersion: v1
kind: Service
metadata:
  name: dashy-service
spec:
  ports:
    - port: 80
      targetPort: 4000
  selector:
    app: dashy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: dashy.jlc.local 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashy-service
            port:
              number: 80
