apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer:latest
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config-volume
          mountPath: /www/assets/config.yml
          subPath: config.yml
      volumes:
      - name: config-volume
        configMap:
          name: homer-config
---
apiVersion: v1
kind: Service
metadata:
  name: homer-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: homer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
  namespace: default
data:
  config.yml: |
    title: "Homelab JLC - TFG"
    subtitle: "Panel de Control de Infraestructura"
    columns: "3"
    connectivityTest: true
    defaults:
      layout: "columns"
      theme: "default"
    
services:
  - name: "Infraestructura & Control"
    icon: "fas check-double"
    items:
      - name: "ArgoCD"
        logo: "assets/tools/argocd.png"
        subtitle: "Despliegue GitOps"
        tag: "infra"
        url: "http://argo.jlc.local"

      - name: "Homer"
        logo: "assets/tools/homer.png"
        subtitle: "Este Dashboard"
        tag: "infra"
        url: "http://homer.jlc.local"

  - name: "Servicios IT"
    icon: "fas network-wired"
    items:
      - name: "Nextcloud"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/nextcloud.png"
        subtitle: "Nube Privada & Almacenamiento"
        tag: "app"
        url: "http://nextcloud.jlc.local"

      - name: "Trilium Notes"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/trilium-notes.png"
        subtitle: "Base de Conocimiento Personal"
        tag: "app"
        url: "http://trilium.jlc.local"
